version: '3'
services:
  url-minimizer1:
    image: url-minimizer
    build:
      context: .
      dockerfile: UrlMinimizer/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - AppInstanceSettings__AppInstanceName=Instance1
    networks:
      - webnet
    
  url-minimizer2:
    image: url-minimizer
    build:
      context: .
      dockerfile: UrlMinimizer/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - AppInstanceSettings__AppInstanceName=Instance2
    networks:
      - webnet
  
  url-minimizer3:
    image: url-minimizer
    build:
      context: .
      dockerfile: UrlMinimizer/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - AppInstanceSettings__AppInstanceName=Instance3
    networks:
      - webnet
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - url-minimizer1
      - url-minimizer2
      - url-minimizer3
    networks:
      - webnet
    
networks:
  webnet:
    
